import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../../comp/SessionWrapper";
import ThemeProvider from '../contexts/theme/ThemeProvider';
import Header from "../layouts/header/Header";
import { GoogleOAuthProvider } from '@react-oauth/google';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SEOGenie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="11585775649-r2ml8fmuq9vsmd679gdkr2kmsnu5e4ms.apps.googleusercontent.com">
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <Header />
        {children}
        </ThemeProvider>
        </body>
    </html>
    </GoogleOAuthProvider>
  );
}
