import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../../comp/SessionWrapper";
import ThemeProvider from "../contexts/theme/ThemeProvider";
import Header from "../layouts/header/Header";
import Footer from "../layouts/footer/Footer";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SEOGenieAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId="11585775649-r2ml8fmuq9vsmd679gdkr2kmsnu5e4ms.apps.googleusercontent.com">
      <html lang="en">
        <head>
        <meta name="google-site-verification" content="feUn5y4_AahF2iqvm1KUeqnJCbVUzQhuJiszt_1_xw4" />
            <GoogleAnalytics gaId="G-P3SWCW993P" />
        </head>
        <body className={inter.className}>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
          <Footer />
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
